name: Auto Merge Exercism Syncer PRs

on:
  schedule:
    # Runs every day at 23:00 UTC (adjust as needed)
    - cron: "0 23 * * *"
  workflow_dispatch: # allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        uses: cli/cli-action@v2
        with:
          version: latest

      - name: Merge PRs opened by exercism-solutions-syncer bot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching open PRs created by app/exercism-solutions-syncer..."
          prs=$(gh pr list --state open --json number,author,headRefName | jq -r '.[] | select(.author.login=="app/exercism-solutions-syncer") | .number')

          if [ -z "$prs" ]; then
            echo "No open PRs from exercism-solutions-syncer."
            exit 0
          fi

          for pr in $prs; do
            echo "Attempting to merge PR #$pr..."
            gh pr merge $pr --merge --auto || echo "Failed to auto-merge PR #$pr"
          done
