name: Auto-merge Exercism Bot PRs

on:
  # Schedule to run once a day, e.g., at 00:00 UTC (midnight)
  schedule:
    - cron: '0 0 * * *' 
  # Allows manual run from the GitHub Actions tab for testing
  workflow_dispatch: 
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge exercism-solutions-syncer PRs
        uses: pascalgn/automerge-action@v0.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Filter to only PRs created by the exercism solutions syncer bot
          MERGE_AUTHOR: 'app/exercism-solutions-syncer'
          # You might want to also filter by label if the bot adds one
          # MERGE_LABELS: 'automerge-exercism' 
          
          # Optional: Select the merge method
          # MERGE_METHOD: 'squash' # or 'merge', 'rebase'
          
          # Optional: Filter for open PRs
          # PULL_REQUEST_STATE: 'open' 
          
          # This should be your main branch (e.g., main, master, development)
          BASE_BRANCHES: 'main'
