name: Auto Merge Exercism Syncer PRs

on:
  schedule:
    # Runs every day at 23:00 UTC (adjust if needed)
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Auto-merge safe Exercism Syncer PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching open PRs created by app/exercism-solutions-syncer..."
          prs=$(gh pr list --state open --json number,author --jq '.[] | select(.author.login=="app/exercism-solutions-syncer") | .number')

          if [ -z "$prs" ]; then
            echo "No open PRs from exercism-solutions-syncer."
            exit 0
          fi

          for pr in $prs; do
            echo "Checking PR #$pr for workflow file changes..."
            changed_files=$(gh pr view $pr --json files --jq '.files[].path')
            if echo "$changed_files" | grep -q "^.github/workflows/"; then
              echo "Skipping PR #$pr (modifies workflow files)"
              continue
            fi

            echo "Merging PR #$pr..."
            gh pr merge $pr --merge --delete-branch || echo "Failed to merge PR #$pr"
          done
